// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { fileURLToPath } from "node:url";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
    // @ts-ignore earlyAccess is a Prisma 7 early-access flag not yet in stable types
    earlyAccess: true,
    schema: fileURLToPath(new URL("./prisma/schema.prisma", import.meta.url)),
    datasource: {
        url: env("DATABASE_URL"),
    },
});
